typesense:
  apiKey:
  storage:
    storageClassName: csi-disk-retain
    size: 40Gi
scraper:
  schedule: '*/2 * * * *'
reverseProxy:
  replicas: 1
  ingress:
    host:
    clusterIssuer: letsencrypt-prod
dashboard:
  replicas: 1
docusaurus:
  externalUrl:
